sonar.projectKey=SebastianLiando_categroove-frontend
sonar.organization=sebastianliando

sonar.coverage.exclusions=**/*.spec.ts,**/categroove-preset.ts,test/setup.ts
sonar.javascript.lcov.reportPaths=./coverage/categroove-frontend/lcov.info
